name: Remove old package versions keeping the last 2
on:
  registry_package:
    types: [published]

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
      - uses: smartsquaregmbh/delete-old-packages@v0.4.0
        with:
          names: kafkajs-snappy-native
          keep: 2
